{
 "title": "Monitoreo MEP",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Conexion Base de Datos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "check_nc{target=\"192.168.172.71\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enlace - BCRA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "check_bcra{target=\"http://ipservidor:puerto/api/v1.1/consulta/estado\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Promedio",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Espacio disponible",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contenedor - prometheus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"localhost:9090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contenedor - node-exporter",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes / 1024^3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM DISPONIBLE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 ^ 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wso2AM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"wso2am\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wso2am-MySql",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"wso2am-mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak-Mysql",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"keycloak-mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"keycloak\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Manager-MySql",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"wso2am-mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reverse-Proxy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"reverse-proxy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mep-APP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"mep-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Manager-App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"manager-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mep-Api",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"mep-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mep-BCRA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"mep-bcra\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mep-Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"mep-redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mep-Rabbitmq",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_status{container=\"mep-rabbitmq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ultimo reinicio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds) / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chequeos Basicos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } }
 ]
}