version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: "prometheus"
    restart: unless-stopped
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - grafana-net

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: "node-exporter"
    restart: unless-stopped
    ports:
    - "9100:9100"
    volumes:
      - ./textfile-collector:/textfile_collector #Aqui configurar siempre el path real en su ambiente
      - /:/host:ro
    command:
      - '--collector.textfile.directory=/textfile_collector'
      - '--path.rootfs=/host'
    networks:
      - grafana-net
    
  grafana:                                                                                                                   
    image: grafana/grafana:10.1.10    
    container_name: "grafana"
    restart: unless-stopped    
    ports:                                                                                                                   
    - "3000:3000"
    volumes:
    - grafana-storage:/var/lib/grafana
    - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - grafana-net

volumes:
  grafana-storage:
 
networks:
  grafana-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
  
