version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: "prometheus"
    restart: unless-stopped
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: "node-exporter"
    restart: unless-stopped
    ports:
    - "9100:9100"
    volumes:
      - /opt/accusys/monitoreo-grafana/textfile-collector:/textfile_collector #Aqui configurar siempre el path real en su ambiente
      - /:/host:ro
    command:
      - '--collector.textfile.directory=/textfile_collector'
      - '--path.rootfs=/host'
    
  grafana:                                                                                                                   
    image: grafana/grafana:10.1.10    
    container_name: "grafana"
    restart: unless-stopped    
    ports:                                                                                                                   
    - "3000:3000"
    volumes:
    - grafana-storage:/var/lib/grafana
    - ./grafana.ini:/etc/grafana/grafana.ini

  advisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: "cadvisor"
    restart: unless-stopped
    ports:
    - "8080:8080"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - /:/rootfs:ro
     - /var/run:/var/run:rw
     - /sys:/sys:ro
     - /var/lib/docker:/var/lib/docker:ro
    devices:
    - /dev/kmsg:/dev/kmsg

volumes:
  grafana-storage:
 
  
