global:                                                                                                                  
    scrape_interval: 15s                                                                                                 
                                                                                                                         
scrape_configs:                                                                                                          
  - job_name: 'prometheus'                                                                                               
    static_configs:                                                                                                      
      - targets: ['localhost:9090']  # Prometheus server                                                                 
  - job_name: 'node-exporter'                                                                                            
    static_configs:                                                                                                      
      - targets: ['node-exporter:9100']  # Node Exporter                                                                 
  - job_name: 'grafana'                                                                                                  
    static_configs:                                                                                                      
      - targets: ['grafana:3000']  # Grafana server 
  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['cadvisor:8080'] # Advisor server    
                                                                                                        
